[package]
name = "librarian"
version = "0.1.0"
authors = ["Jason Rogena <jason@rogena.me>"]
edition = "2018"
rust-version = "1.61"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.137"
serde_derive = "1.0.137"
toml = "0.5.9"
regex = "1"
tree_magic = "0.2.3"
tera = "1"
